service: templateService # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

package:
  individually: true

functions:
  getExample:
    handler: src/getHandler.getFunction
    package:
      exclude:
        - ./**
      include:
        - src/getHandler.js
    events:
      - http:
          path: get/{name}
          method: get
          request: 
            parameter:
              paths:
                name: true
  postExample:
    handler: src/postHandler.postFunction
    package:
      exclude:
        - ./**
      include:
        - src/postHandler.js
    events:
      - http:
          path: post
          method: post
